name: hello-world

on: 
  push:
    branches:
      - main  # Specify branches if needed (e.g., 'main')

jobs:  
  my-job:
    runs-on: ubuntu-latest

    steps: 
      - name: my-step
        run: echo "Hello world"
